- name: S'assurer que Docker et Compose sont installés
  ansible.builtin.apt:
    name:
      - docker.io
      - docker-compose-plugin
    state: present
    update_cache: yes

- name: S'assurer que le service Docker est démarré et activé
  ansible.builtin.systemd:
    name: docker
    state: started
    enabled: yes

- name: Créer le dossier pour la douane
  ansible.builtin.file:
    path: /opt/douane_gateway
    state: directory

- name: Déployer le fichier docker-compose.yml
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: /opt/douane_gateway/docker-compose.yml

- name: Démarrer Traefik et les tunnels
  community.docker.docker_compose_v2:
    project_src: /opt/douane_gateway
    state: present